title: Left Fetch Blog
email: f.versnel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about software engineering and game development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.leftfetch.com"
twitter_username: fversnel
github_username:  fversnel

# Build settings
markdown: kramdown
