title: Left Fetch Blog
email: frank@leftfetch.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about software engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leftfetch.com"
twitter_username: fversnel
github_username:  fversnel

# Build settings
markdown: kramdown

# theme: jekyll-theme-slate