version: '3'
services:
  blog:
    container_name: leftfetch-blog
    image: jekyll/jekyll:3.8
    ports:
    - 4000:4000
    volumes:
    - ./:/srv/jekyll:Z
    command: jekyll serve --watch --draft
